app/blueprints/characters/models.py
from app import db
from datetime import datetime as dt

class Character(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    description = db.Column(db.String)
    comics_appeared_in = db.Column(db.Integer)
    super_power = db.Column(db.String)
    date_created = db.Column(db.DateTime, default=dt.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def to_dict(self):
        from app.blueprints.auth.models import User

        data = {
            'name': self.name,
            'description': self.description,
            'comics_appeared_in': self.comics_appeared_in,
            'super_power': self.super_power,
            'user': User.query.get(self.user_id).to_dict()
        }
        return data

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_moment import Moment

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()
moment = Moment()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app) 
    moment.init_app(app)

    from app.blueprints.main import bp as main
    app.register_blueprint(main)

    from app.blueprints.auth import bp as auth
    app.register_blueprint(auth)

    from app.blueprints.characters import bp as characters
    app.register_blueprint(characters)

    from app.blueprints.users import bp as users
    app.register_blueprint(users)

    from app.blueprints.api import bp as api
    app.register_blueprint(api)



    return app

app/blueprints/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__, url_prefix='/api')

from . import users, tokens, characters

app/blueprints/api/auth.py
from flask_httpauth import HTTPBasicAuth, HTTPTokenAuth
from app.blueprints.auth.models import User

basic_auth = HTTPBasicAuth()
token_auth = HTTPTokenAuth()

@basic_auth.verify_password
def verify_password(email, password):
    u = User.query.filter_by(email=email).first()
    if u and u.check_password(password):
        return u


@token_auth.verify_token
def verify_token(token):
    return User.check_token(token) if token else None

app/blueprints/characters/__init__.py
from flask import Blueprint

bp = Blueprint('characters', __name__, url_prefix="/characters")

from . import routes, models

app/blueprints/characters/routes.py
from os import name, stat
from . import bp as app
from app import db
from flask import render_template, url_for, redirect, request, flash
from datetime import date, datetime
from app.blueprints.auth.models import User
from app.blueprints.characters.models import Character
from flask_login import login_user, logout_user, current_user

@app.route('/')
def home():

    context = {
        'characters': Character.query.order_by(Character.date_created.desc()).all()
    }
    return render_template('characters/index.html', **context)

@app.route('/new', methods=['GET', 'POST'])
def new():
    if request.method == 'POST':
        if Character.query.filter_by(name=request.form.get('name')).first() is not None:
            flash('There is already a character under that name.', 'warning')
            return redirect(url_for('characters.home'))
        c = Character(
            name=request.form.get('name'),
            description=request.form.get('description'),
            comics_appeared_in=int(request.form.get('comics_appeared_in')),
            super_power=request.form.get('super_power'),
            user_id = current_user.get_id()
        )
        db.session.add(c)
        db.session.commit()
        flash('Character added!', 'success')
        return redirect(url_for('characters.home'))
    return render_template('characters/new.html')


@app.route('/<id>')
def char(id):
    current_char = None
    try:
        if id.isdigit():
            current_char = Character.query.get(id)

            if current_char == None:
                raise ValueError(f'Character {id} not found')
        else:
            raise ValueError(f'ID: {id} is not valid')
    except ValueError as e:
        flash(str(e), 'danger')
    context = {
        'char': current_char
    }
    return render_template('characters/char.html', **context)

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, url_prefix="/")

from . import routes, models

app/blueprints/main/routes.py
from os import stat
# from app import app, db
from . import bp as app
from app import db
from flask import render_template, url_for, redirect, request, flash
from datetime import date, datetime
from app.blueprints.auth.models import User
from flask_login import login_user, logout_user, current_user

@app.route('/')
def home():
    return render_template('index.html')

app/blueprints/users/__init__.py
from flask import Blueprint

bp = Blueprint('users', __name__, url_prefix="/users")

from . import routes, models

app/blueprints/users/routes.py
from os import name, stat
from . import bp as app
from app import db
from flask import render_template, url_for, redirect, request, flash
from datetime import date, datetime
from app.blueprints.auth.models import User
from app.blueprints.characters.models import Character
from flask_login import login_user, logout_user, current_user

@app.route('/')
def home():

    context = {
        'users': User.query.order_by(User.date_created.desc()).all()
    }
    return render_template('users/index.html', **context)

@app.route('/<id>')
def user(id):
    current_u = None
    try:
        if id.isdigit():
            current_u = User.query.get(id)

            if current_u == None:
                raise ValueError(f'User {id} not found')
        else:
            raise ValueError(f'ID: {id} is not valid')
    except ValueError as e:
        flash(str(e), 'danger')
    context = {
        'user': current_u,
        'characters': Character.query.filter_by(user_id=id).order_by(Character.date_created.desc()).all()
    }
    return render_template('users/user.html', **context)

@app.route('/profile', methods=['GET', 'POST'])
def profile():
    u = User.query.get(current_user.get_id())
    context = {
        'characters': Character.query.filter_by(user_id=u.get_id()).order_by(Character.date_created.desc()).all()
        # 'posts': Post.query.filter_by(user=u).all()
    }
    if request.method == 'POST':
        f_name = request.form.get('f_name')
        l_name = request.form.get('l_name')
        email = request.form.get('email')
        password = request.form.get('password')
        confirm_password = request.form.get('confirm_password')

        if not password and not confirm_password:
            u.first_name = f_name
            u.last_name = l_name
            u.email = email
            db.session.commit()
            flash('You have successfully updated your profile', 'info')
            return redirect(request.referrer)
        else:
            if password == confirm_password:
                u.first_name = f_name
                u.last_name = l_name
                u.email = email
                u.generate_password(password)
                db.session.commit()
                flash('You have successfully updated your profile', 'info')
                return redirect(request.referrer)
            else:
                flash('Your passwords do not match. try again', 'danger')
                return redirect(request.referrer)
            
    return render_template('users/profile.html', **context)

app/templates/characters/char.html
{% extends 'layout.html' %}

{% block content %}


{% if char != None %}

<h3>{{ char.name  }}</h3>

<div>
    
    <ul class="list-group">
            <li class="list-group-item">
                <p>Description: {{ char.description }}</p>
                <p>Number of comics appears in: {{ char.comics_appeared_in }}</p>
                <p>Super Powers: {{ char.super_power }}</p>
                <p>Added by {{ char.user.first_name }} on {{  char.date_created  }}</p>
            </li>
        </ul>
        
    </div>
    
    
{% endif %}
{% endblock content %}

app/templates/characters/index.html
{% extends 'layout.html' %}

{% block content %}



<div>
    <h3>Characters</h3>
    <hr>

    <div class="card-deck row">

        {% for c in characters %}
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="{{ url_for('characters.char', id=c.id) }}">{{ c.name }}</a>
                    </h4>
                    <p class="card-text">{{ c.description|truncate(50, True) }}</p>
                    <p class="card-text">Powers: {{ c.super_power }}</p>
                </div>
            </div>

        </div>
        {% endfor %}
    </div>


</div>


{% endblock content %}

app/templates/characters/new.html
{% extends 'layout.html' %}

{% block content %}

      
      
      <div>
          <h3>Add a New Character</h3>
          <hr>

          <form action="{{ url_for('characters.new') }}" method="post">
              <div class="form-group">
                  <input type="text" placeholder="Character Name" name="name" class="form-control">
              </div>
              <div class="form-group">
                  <input type="text" placeholder="Description" name="description" class="form-control">
              </div>
              <div class="form-group">
                  <input type="text" placeholder="Comics Character Appears In (number)" name="comics_appeared_in" class="form-control">
              </div>
              <div class="form-group">
                  <input type="text" placeholder="Super Powers" name="super_power" class="form-control">
              </div>

              
              <input type="submit" class="btn btn-primary btn-block" value="Add Character">
          </form>


      </div>
      
      
{% endblock content %}

app/templates/index.html
{% extends 'layout.html' %}

{% block content %}



<div>
    <h3>
        Home
        {% if current_user.is_authenticated %}
            | Welcome {{ current_user.first_name }} {{ current_user.last_name }} ({{ current_user.email }})
        {% endif %}
    </h3>
    
    <hr>



</div>


{% endblock content %}

app/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <title>Marvel</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
      <header>
          {% include './partials/navbar.html' %}
      </header>

      <main class="container">

        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for c, m in messages %}
                    <div class="alert alert-{{ c }} alert-dismissible fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            <span class="sr-only">Close</span>
                        </button>
                        <strong>{{ m }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        
        {% block content %}
        {% endblock content %}  
      </main>
      
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/partials/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url_for('main.home') }}">MARVEL</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('characters.home') }}">Characters</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.home') }}">Users</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if not current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('characters.new') }}">Add a New Character</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.profile') }}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                </li>
            {% endif %}
        </ul>
    </div>
 </nav>

app/templates/users/index.html
{% extends 'layout.html' %}

{% block content %}



<div>
    <h3>Users</h3>
    <hr>

    <div class="card-deck row">

        {% for u in users %}
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="{{ url_for('users.user', id=u.id) }}">{{ u.first_name }} {{ u.last_name }}</a>
                    </h4>
                    <p class="card-text">{{ u.email }}</p>
                </div>
            </div>

        </div>
        {% endfor %}
    </div>


</div>


{% endblock content %}

app/templates/users/profile.html
{% extends 'layout.html' %}

{% block content %}

<div>
    <h3>Profile</h3>
    <hr>

    <div class="row">
        <div class="col-3">
            <img src="https://via.placeholder.com/500/1000" alt="Profile Image" class="img-fluid">
        </div>
        <div class="col-9">
            <form action="{{ url_for('users.profile') }}" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <div class="row">
                        <div class="col-6">
                            <input type="text" value="{{ current_user.first_name }}"class="form-control" name="f_name">
                        </div>
                        <div class="col-6">
                            <input type="text" value="{{ current_user.last_name }}"class="form-control" name="l_name">
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <input type="file" placeholder="Image" name="image" calss="form-control-file">
                </div>
                <div class="form-group">
                    <input type="email" value="{{ current_user.email }}" name="email" calss="form-control">
                </div>
                <div class="form-group">
                    <input type="password" placeholder="Password" name="password" calss="form-control">
                </div>
                <div class="form-group">
                    <input type="password" placeholder="Confirm Password" name="confirm_password" calss="form-control">
                </div>
                <input type="submit" value="Update Profile" calss="btn btn-info btn-block">
            </form>
        </div>
    </div>

    <hr>


<div>
    <h3>Your Characters</h3>
    <hr>

    <div class="card-deck row">

        {% for c in characters %}
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="{{ url_for('characters.char', id=c.id) }}">{{ c.name }}</a>
                    </h4>
                    <p class="card-text">{{ c.description|truncate(50, True) }}</p>
                    <p class="card-text">Powers: {{ c.super_power }}</p>
                </div>
            </div>

        </div>
        {% endfor %}
    </div>


</div>


{% endblock content %}

app/templates/users/user.html
{% extends 'layout.html' %}

{% block content %}



<div>
    <h3>{{  user.first_name  }} {{  user.last_name  }}'s Characters</h3>
    <hr>

    <div class="card-deck row">

        {% for c in characters %}
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="{{ url_for('characters.char', id=c.id) }}">{{ c.name }}</a>
                    </h4>
                    <p class="card-text">{{ c.description|truncate(50, True) }}</p>
                    <p class="card-text">Powers: {{ c.super_power }}</p>
                </div>
            </div>

        </div>
        {% endfor %}
    </div>


</div>


{% endblock content %}